#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Build and push container

on:
  push:
    branches:
      - 'master'

jobs:
  define_platforms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo ::set-env name=platforms::$(cat .platforms)
  pre-compiler:
    strategy:
      matrix:
        platform: ${{ steps.define_platforms.platforms }}
    env:
      IMAGE_NAME: quay.io/eclipse/che-custom-nodejs-deasync
    runs-on: ubuntu-latest
    steps:
    - name: Clone source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: quay.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.5.0
      with:
        version: v0.3.1
    - name: Docker build, tag, and push
      run: |
        IMAGE_VERSION=$(cat VERSION)
        PLATFORM=$(echo ${{matrix.platform}} | tr '\/' '-') 
        IMAGE_WITH_TAG="${IMAGE_NAME}:${IMAGE_VERSION}-${PLATFORM}-compile"
        echo "Building ${IMAGE_WITH_TAG} on platform ${{matrix.platform}}"
        