#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: PR check of the Docker container

# Trigger the workflow on push or pull request
on: [push, pull_request]


env:
  IMAGE_NAME: che-dockerfiles/che-custom-nodejs-deasync

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Docker build and test
      run: |
        echo "Building ${IMAGE_NAME}"
        docker build -t "${IMAGE_NAME}" .
        echo "Testing ${IMAGE_NAME}"
        docker build -t "${IMAGE_NAME}-test" -f Dockerfile.test
